# Generated by Django 4.0.10 on 2023-03-07 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.utcnow, verbose_name='Created At')),
                ('last_modified', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.utcnow, verbose_name='Last Modified At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('deactivated_at', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Deactivated At')),
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Question ID')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name='Title')),
                ('context', models.TextField(db_index=True, max_length=256, verbose_name='Title')),
                ('canonical_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_answer', to='answers.answer')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
            },
        ),
    ]
