# Generated by Django 4.0.10 on 2023-03-07 22:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.utcnow, verbose_name='Created At')),
                ('last_modified', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.utcnow, verbose_name='Last Modified At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('deactivated_at', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Deactivated At')),
                ('topic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Topic ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Topic Title')),
            ],
            options={
                'verbose_name': 'Question Topic',
                'verbose_name_plural': 'Question Topics',
                'db_table': 'question_topic',
            },
        ),
    ]
