# Generated by Django 4.0.10 on 2023-03-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontopic',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Topic Title'),
        ),
    ]
